language: "node_js"
node_js:
    - "4"
    - "5"
    - "6"
addons:
    apt:
        packages:
            - libldap2-dev
before_install:
    - npm install -g mocha
    - npm install -g yarn
install:
    - yarn install
script:
    - mocha test
notifications:
    email: false
