language: "node_js"
node_js:
    - "4"
    - "5"
    - "6"
env:
    - CXX=g++-4.8
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
            - slapd
            - libldap2-dev
            - ldap-utils
before_install:
    - npm install -g mocha
    - npm install -g yarn
install:
    - yarn install
script:
    - mocha test
notifications:
    email: false
